brabbl/accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.UserRetrieveUpdateAPIView.as_view(), name='user-profile'),
    url(r'^login/$', views.UserLoginAPIView.as_view(), name='user-login'),
    url(r'^logout/$', views.UserLogoutAPIView.as_view(), name='user-logout'),
    url(r'^register/$', views.UserCreateAPIView.as_view(), name='user-create'),
    url(r'^reset/$', views.PasswordResetAPIView.as_view(), name='user-reset-password'),
    url(r'^confirm-data-policy/$',
        views.ConfirmDataPolicyView.as_view(), name='user-confirm-data-policy'),
]

brabbl/api/urls.py
from django.conf.urls import include, url

from brabbl.accounts import urls as accounts_urls, views
from brabbl.core import urls as core_urls

app_name = 'api'
urlpatterns = [
    url(r'^account/', include(accounts_urls)),
    url(r'^', include(core_urls)),
    url(r'^accounts/user-list-update/$', views.UserListUpdateAPIView.as_view(), name='user-list-update'),
]

brabbl/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required

from brabbl.accounts.views import (
    PasswordResetView, WelcomeView, UserListView
)
from brabbl.core.views import DuplicateObject
from brabbl.api import urls as api_urls

urlpatterns = [
    url(r'^api/v1/', include(api_urls, namespace='v1')),
    url(r'^admin/core/duplicate/(?P<model>[^/]+)/(?P<pk>[0-9]+)/',
        staff_member_required(DuplicateObject.as_view()),
        name="duplicate-object"),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/rq/', include('django_rq.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),

    url(r'^accounts/verify/(?P<token>[^/]+)/$', WelcomeView.as_view(),
        name='verify-registration'),
    url(r'^accounts/reset/(?P<token>[^/]+)/$', PasswordResetView.as_view(),
        name='reset-password'),
    url(r'^accounts/user-list/$', UserListView.as_view(), name='user-list'),
    url(r'^welcome/$', WelcomeView.as_view(), name='welcome-account'),
    url(r'^test/$', TemplateView.as_view(template_name='whitelabel.html')),
    url(r'^embed\.(css|js)$', TemplateView.as_view(template_name='embed.js',
                                                   content_type='application/js')),
]
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^rosetta/', include('rosetta.urls')),

if settings.DEBUG:
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

brabbl/accounts/forms.py
from datetime import datetime

from django import forms
from django.forms import widgets
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class WelcomeForm(forms.Form):
    first_name = forms.CharField(label=_("First Name"), required=False)
    last_name = forms.CharField(label=_("Last Name"), required=False)
    gender = forms.IntegerField(
        label=_("Gender"), required=False, widget=widgets.Select(choices=User.GENDER_LIST)
    )
    year_of_birth = forms.IntegerField(label=_("Year of birth"),
                                       min_value=datetime.now().year-150,
                                       max_value=datetime.now().year,
                                       required=False,
                                       widget=forms.TextInput())
    postcode = forms.CharField(label=_("Postcode"), required=False)
    city = forms.CharField(label=_("City"), required=False)
    bundesland_list = list(User.BUNDESLAND_LIST)
    bundesland = forms.CharField(
        label=_("Bundesland"), required=False, widget=widgets.Select(choices=bundesland_list)
    )
    country = forms.CharField(label=_("Country"), required=False)
    organization = forms.CharField(label=_("Organization"), required=False)
    position = forms.CharField(label=_("Position"), required=False)

    def __init__(self, *args, **kwargs):
        _exclude_fields = kwargs.pop('exclude_fields', [])
        super().__init__(*args, **kwargs)
        for item in self.fields.copy():
            if item not in _exclude_fields:
                self.fields.pop(item)
            elif _exclude_fields[item]:
                self.fields[item].required = True

brabbl/accounts/views.py
from brabbl.accounts.authentication import BrabblIFrameTokenAuthentication
from django.core.validators import URLValidator
from django.utils.decorators import method_decorator
from django.utils.timezone import localtime, now
from django.views.decorators.clickjacking import xframe_options_exempt
from rest_framework import generics, views, status
from rest_framework.authtoken.models import Token
from rest_framework.exceptions import NotAuthenticated, ValidationError, PermissionDenied
from rest_framework.response import Response
from social_django.utils import load_strategy

from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import Group
from django.views.generic import TemplateView, FormView
from django.shortcuts import redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from brabbl.accounts import serializers
from brabbl.accounts.forms import WelcomeForm
from brabbl.accounts.models import Customer
from brabbl.accounts.social import partial_load
from brabbl.core.models import MarkdownWordingMessage
from brabbl.core.permissions import IsAuthenticated
from brabbl.utils import language_utils
from brabbl.utils.http import get_next_url
from brabbl.utils.models import delete_all_unexpired_sessions_for_user


class WelcomeView(FormView):
    template_name = 'accounts/welcome.html'
    form_class = WelcomeForm
    customer_token = None

    def get(self, *args, **kwargs):
        if self.request.GET.get('cancel') is not None:
            return self.complete_redirect()
        return super().get(*args, **kwargs)

    def complete_redirect(self):
        user = self.get_token_user()
        if user:
            user.activate()
            next_url = self.request.GET.get('next')
            val = URLValidator()
            try:
                val(next_url)
            except ValidationError:
                if user:
                    next_url = user.customer.allowed_domains.splitlines()[0]
            return redirect(next_url)

        self.get_customer(user)
        self.request.session.modified = True
        partial_token = self.request.session.get('partial_pipeline_token')
        strategy = load_strategy(self.request)
        strategy.session_set('user_created', True)
        backend = partial_load(strategy, partial_token, self.customer_token).backend
        return redirect('social:complete', backend=backend)

    def get_customer(self, user=None):
        if not user:
            user = self.get_token_user()
        if user:
            return user.customer
        self.customer_token = self.request.session.get('customer_token', '')
        return get_object_or_404(Customer, embed_token=self.customer_token)

    def get_context_data(self, *args, **kwargs):
        user = self.get_token_user()
        customer = self.get_customer(user)
        # set language for user by customer
        self.request = language_utils.set_language(
            self.request, customer.language
        )
        context = super().get_context_data(*args, **kwargs)
        context['wording'] = {
            'welcome_title': _("Welcome"),
            'welcome_text_social': _(
                """By signing up, you agree to %s Basic Rules, Terms of Service, and Privacy Policy.<br/>
        Have fun discussing on customer page. This text should be customizable.<br/>
        Please update the following required fields"""
            ) % customer.name
        }
        if self.kwargs.get('token'):
            context['wording']['welcome_text_social'] = _(
                """Thank you very much. Your brabbl account at {}
                has been successfully activated."""
            ).format(customer.domain)
        if customer.notification_wording:
            wordings = MarkdownWordingMessage.objects.filter(
                property_model__pk=customer.notification_wording,
                key__in=['welcome_title', 'welcome_text_social']
            )
            for wording in wordings:
                if wording.key == 'welcome_title':
                    if wording.value:
                        context['wording']['welcome_title'] = wording.value
                if wording.key == 'welcome_text_social':
                    if wording.value:
                        context['wording']['welcome_text_social'] = wording.value
        context['CUSTOMER_THEME'] = customer.theme

        return context

    def get_user(self):
        self.get_customer()
        partial_token = self.request.session.get('partial_pipeline_token')
        strategy = load_strategy(self.request)
        partial_pipeline = partial_load(strategy, partial_token, self.customer_token)
        try:
            pk = partial_pipeline.kwargs.get('user', None).pk
        except AttributeError:
            pk = None
        return get_user_model().objects.filter(id=pk)

    def get_token_user(self):
        User = get_user_model()
        token = self.kwargs.get('token')
        if not token:
            return None
        try:
            return User.objects.get_by_token(self.kwargs.get('token'))
        except User.DoesNotExist:
            return None

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        result = {}
        user = self.get_user().values()
        if user and user[0]:
            result = user[0]
        else:
            user = self.get_token_user()
            if user:
                result = user.__dict__
        return result

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        customer = self.get_customer()
        kwargs['exclude_fields'] = dict(customer.model_properties.filter(
            show_in_welcome=True
        ).values_list('key', 'is_required'))
        return kwargs

    def form_valid(self, form):
        if form.is_valid():
            user = self.get_token_user()
            if user:
                for item in form.cleaned_data:
                    setattr(user, item, form.cleaned_data[item])
                user.save()
            else:
                self.get_user().update(**form.cleaned_data)
        return self.complete_redirect()


class UserLoginAPIView(views.APIView):
    def post(self, request):
        serializer = serializers.UserAuthTokenSerializer(
            data=request.data,
            context={'request': request},
        )
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'has_accepted_current_data_policy': user.has_accepted_current_data_policy()
        })


class UserLogoutAPIView(views.APIView):
    def get(self, request):
        if self.request.user.is_authenticated:
            delete_all_unexpired_sessions_for_user(user=self.request.user)
            logout(self.request)

        return Response(status=status.HTTP_204_NO_CONTENT)


class UserRetrieveUpdateAPIView(generics.RetrieveUpdateAPIView):
    model = get_user_model()
    permission_classes = [IsAuthenticated]
    serializer_class = serializers.UserSerializer

    def get_object(self):
        if self.request.user and self.request.user.is_authenticated:
            return self.request.user
        raise NotAuthenticated()


class UserCreateAPIView(generics.CreateAPIView):
    model = get_user_model()
    serializer_class = serializers.UserCreateSerializer


class PasswordResetAPIView(views.APIView):
    def post(self, request, *args, **kwargs):
        serializer = serializers.UserEmailSerializer(
            data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)

        UserModel = get_user_model()
        user = UserModel._default_manager.get(customer=request.customer, email__iexact=serializer.data['email'],
                                              is_active=True)

        user.send_password_reset_mail(request.customer,
                                      source_url=request.META.get('HTTP_REFERER'))
        return Response(status=status.HTTP_204_NO_CONTENT)


class ConfirmDataPolicyView(views.APIView):

    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):

        def get_client_ip(request):
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            return ip
        if not request.user.has_accepted_current_data_policy():
            if request.user.customer.data_policy_version:
                request.user.datapolicyagreements.create(
                    user=request.user,
                    data_policy=request.user.customer.data_policy_version,
                    ip_address=get_client_ip(request),
                    date_accepted=localtime(now())
                )
        return Response(status=status.HTTP_204_NO_CONTENT)


class PasswordResetView(FormView):
    template_name = 'accounts/password_reset.html'
    form_class = SetPasswordForm

    def get_user(self):
        User = get_user_model()
        token = self.kwargs.get('token', None)

        try:
            return User.objects.get_by_token(token)
        except User.DoesNotExist:
            return None

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.get_user(), **self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super(PasswordResetView, self).get_context_data(**kwargs)
        user = self.get_user()
        theme = Customer.THEME_BRABBL
        if user:
            # set language for user by customer
            self.request = language_utils.set_language(

brabbl/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load i18n url_tags %}

{% block meta %}
  {{ block.super }}
  {% if success and next %}
    <meta http-equiv="refresh" content="5; URL={{ next }}">
  {% endif %}
{% endblock %}

{% block content_title %}
  {% if success %}
    {% trans "Password has been reset" %}
  {% else %}
    {% trans "Reset password" %}
  {% endif %}
{% endblock %}

{% block content_main %}
  {% if user %}
    {% if success %}
      <p>
        {% blocktrans with customer_url=next|domain %}Password of your brabbl account at {{customer_url}} has been changed successfully.{% endblocktrans %}

        {% if next %}
            {% trans "In a few moments you will be redirected to" %}
            <a href="{{ next }}">{{ next|strip_http }}</a>
        {% endif %}
      </p>
    {% else %}
      <form method="post">{% csrf_token %}
        {% if form.non_field_errors %}
          <div class="err">
            <ul class="errorlist">
              {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
        <div class="row {% if form.new_password1.errors %}err{% endif %}">
          <label for="id_new_password1">{% trans "New password" %}:</label>
          {{ form.new_password1 }}
          {% if form.new_password1.errors %}
            <ul class="errorlist">
              {% for error in form.new_password1.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
        <div class="row {% if form.new_password2.errors %}err{% endif %}">
          <label for="id_new_password2">{% trans "Confirm password" %}:</label>
          {{ form.new_password2 }}
          {% if form.new_password2.errors %}
            <ul class="errorlist">
              {% for error in form.new_password2.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
        <div class="fullform-footer">
          <button class="primary">{% trans "Change password" %}</button>
        </div>
      </form>
    {% endif %}
  {% else %}
    <p>
      {% trans "The link you used is invalid or has already been used. Please request a new confirmation link." %}
    </p>
  {% endif %}
{% endblock %}

brabbl/templates/accounts/user_list.html
{% extends "iframe.html" %}
{% load i18n url_tags getattribute user_additional_info %}

{% block meta %}
    {{ block.super }}
    {% if success and next %}
        <meta http-equiv="refresh" content="5; URL={{ next }}">
    {% endif %}
{% endblock %}

{% block content_title %}
    {% trans "User List" %}
{% endblock %}
{% block styles %}
{% endblock %}

{% block content_main %}
    <div class="user-list">
        {% for user in users %}
            <div class="row">
                <div class="manage-block" id="user-{{ user.id }}">
                    <form method="post">{% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <div class="form-field">
                            <label for="is_active">{% trans "Active" %}</label>
                            <input name="is_active"
                                   {% if user.is_active %}checked{% endif %}
                                   type="checkbox">
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-field">
                            <select name="group">
                                {% with user.groups.all as user_groups %}
                                    <option value="">{% trans "User" %}</option>
                                    {% for group in groups %}
                                        <option value="{{ group.id }}"
                                                {% if group in user_groups %}
                                                selected="selected"
                                                {% endif %}
                                        >{{ group.name }}</option>
                                    {% endfor %}
                                {% endwith %}
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
                <div class="user-data">
                    <div class="avatar">{% get_thumbnail user.image "128x128" %}</div>
                    <div><b>{{ user.display_name }}</b></div>
                    {% user_additional_info user additional_info display_fullname %}
                </div>
                <div class="clearfix"></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block powered-by %}{% endblock %}
{% block javascript %}
    <script type="text/javascript">
        $(".manage-block form input, .manage-block form select").change(function () {
            var data = $(this).closest('form').serializeArray();
            $.ajax({
                type: "POST",
                url: "{% url 'v1:user-list-update' %}",
                data: data,
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-Brabbl-Token', '{{ customer.embed_token }}')
                    xhr.setRequestHeader('Authorization', 'Token {{ user_token }}');
                },
                success: function (data) {
                },
            });
        });
    </script>
{% endblock %}

brabbl/templates/accounts/welcome.html
{% extends 'base.html' %}
{% load url_tags i18n %}

{% block meta %}
{% endblock %}

{% block content_title %}
    {{ wording.welcome_title|striptags }}
{% endblock %}

{% block content_main %}
  <div>
    <p>
        {{ wording.welcome_text_social|safe }}
    </p>
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <div class="row form-field">
              {{ field.errors }}
              <label for="{{ field.auto_id }}">{{ field.label }}</label>
              <span> </span>
              {{ field }}
              <span></span>
            </div>
          {% endfor %}
          <div class="fullform-footer">
            <button class="primary" type="submit">{% trans "Finish sign up" %}</button>
          </div>
        </form>
  </div>
{% endblock %}